### ISSUE TITLE
After update using built in update tool 'Relauncher' pinned a core at 100%

### ISSUE THREAD

**Issue by hjmallon** [DigiDNA/ISOBMFF-Explorer#2] opened 2020-04-17 12:49 UTC
It prompted me to update, so I did. It never relaunced automatically. I noticed the fan was spinning up on my laptop later on and it was because 'Relauncher' was pinning a core at 100% and it was trying to do something with ISOBMFF-Explorer.

macOS 10.15

**Comment by macmade** [comment] 2020-04-20 13:20
Thanks for the report.
I was not able to reproduce this particular issue, but that's true that the standalone version has some issues with the new permission system of macOS 10.15.

You may use the AppStore version instead, which isn't impacted by those issues:
https://apps.apple.com/ch/app/isobmff-explorer/id1300778278?l=en&mt=12

I'm closing the issue for now, feel free to reopen one if you have other questions. : )

**Closed as completed by macmade** 2020-04-20 13:20 UTC
